matrix/Models/Views/HomeViewModel.cs
using matrix.Models.Entidades;

namespace matrix.Models.Views
{
    public class HomeViewModel
    {
        public List<ServicoViewModel> servicos { get; set; }
        public List<PostagemViewModel> Postagens { get; set; }
    }
}

matrix/Controllers/HomeController.cs
using AutoMapper;
using matrix.Dominio;
using matrix.Dominio.Interfaces.Repository;
using matrix.Models;
using matrix.Models.Entidades;
using matrix.Models.Views;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace matrix.Controllers
{
    public class HomeController : Controller
    {
        private readonly IServicoRepository _servicoRepository;
        private readonly IPostagemRepository _postagemRepository;
        private readonly IMapper _mapper;
        public HomeController(IServicoRepository servicoRepository, IPostagemRepository postagemRepository, IMapper mapper)
        {
            _servicoRepository = servicoRepository;
            _postagemRepository = postagemRepository;
            _mapper = mapper;
        }


        public IActionResult Index()
        {
            var homeModel = new HomeViewModel();
            var listaServicos = _servicoRepository.ObterServicosPaginaInicial();
            List<ServicoViewModel> listViewServico = _mapper.Map<List<ServicoViewModel>>(listaServicos);

            var listaPostagem = _postagemRepository.ObterPostagensPaginaPrincipal();
            List<PostagemViewModel> listViewPostagem = _mapper.Map<List<PostagemViewModel>>(listaPostagem);


            homeModel.servicos = listViewServico;
            homeModel.Postagens = listViewPostagem;
            return View(homeModel);
        }

        [Authorize(Roles = "Administrador")]
        public IActionResult Administrador()
        {
            return View();
        }

    }
}

matrix/Controllers/PostagemsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using matrix.Dominio;
using matrix.Models.Entidades;
using matrix.Dominio.Interfaces.Repository;
using matrix.Models.Views;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace matrix.Controllers
{

    public class PostagemsController : Controller
    {
        private readonly IPostagemRepository _postagemRepository;
        private readonly UserManager<Pessoa> _userManager;
        private readonly IMapper _mapper;

        public PostagemsController(IPostagemRepository postagemRepository, IMapper mapper, UserManager<Pessoa> userManager)
        {
            _postagemRepository = postagemRepository;
            _userManager = userManager;
            _mapper = mapper;

        }

        public async Task<IActionResult> Index()
        {
            var listaPostagem = _postagemRepository.ObterTodos();
            List<PostagemViewModel> listViewPostagem = _mapper.Map<List<PostagemViewModel>>(listaPostagem);
            return View(listViewPostagem);
        }

        public async Task<IActionResult> Details(int id)
        {
            var Postagem = _postagemRepository.ObterPorId(id);
            var postagemViewModel = _mapper.Map<PostagemViewModel>(Postagem); 
            return View(postagemViewModel);
        }

        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            ViewBag.idPost = new SelectList(_mapper.Map<List<PostagemViewModel>>(_postagemRepository.ObterTodos()), "PostagemViewModel.NomePessoa");
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create(PostagemViewModel postagemView)
        {
            if (ModelState.IsValid)
            {
                var postagemModel = _mapper.Map<Postagem>(postagemView);
                postagemModel.PessoaId = _userManager.GetUserId(User);
                postagemModel.Date = DateTime.Now;
                _postagemRepository.CriarNovo(postagemModel);
                _postagemRepository.Salvar();
                return RedirectToAction(nameof(Index));
            }
            ViewData["idPost"] = new SelectList(_postagemRepository.ObterTodos(), "idPost", "idPost", postagemView.idPost);
            return View(postagemView);
            
        }

        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Postagem = _postagemRepository.ObterPorId(id);
            var postagemViewModel = _mapper.Map<PostagemViewModel>(Postagem);
            if (postagemViewModel == null)
            {
                return NotFound();
            }
            
            
            return View(postagemViewModel);
        }

       
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int id, PostagemViewModel postagemView)
        {
            if (id != postagemView.idPost)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                     var postagemModel = _mapper.Map<Postagem>(postagemView);
                     postagemModel.PessoaId = _userManager.GetUserId(User);
                     //postagemModel.Date = _postagemRepository.ObterDate(postagemModel.idPost);
                    _postagemRepository.Atualizar(postagemModel);
                    _postagemRepository.Salvar();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_postagemRepository.Exists(postagemView.idPost))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(postagemView);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var postagem = _postagemRepository.ObterPorId(id);
            _postagemRepository.Deletar(postagem);
            _postagemRepository.Salvar();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult ListaPostagens()
        {
            var postagensModel = _postagemRepository.ObterTodos();
            var postagensView = _mapper.Map<List<PostagemViewModel>>(postagensModel);
            return View(postagensView);
        }

    }
}

matrix/Controllers/ServicosController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using matrix.Dominio;
using matrix.Models.Entidades;
using matrix.Dominio.Interfaces.Repository;
using matrix.Models.Views;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace matrix.Controllers
{
    public class ServicosController : Controller
    {
        private readonly IServicoRepository _servicoRepository;
        private readonly IEquipeRepository _equipeRepository;
        private readonly UserManager<Pessoa> _userManager;
        private readonly IMapper _mapper;


        public ServicosController(IServicoRepository servicoRepository, IMapper mapper, IEquipeRepository equipeRepository, UserManager<Pessoa> userManager)
        {
            _servicoRepository = servicoRepository;
            _equipeRepository = equipeRepository;
            _userManager = userManager;
            _mapper = mapper;
        }

        // GET: Servicos
        public async Task<IActionResult> Index()
        {
            var listaServicos = _servicoRepository.ObterTodos();
            List<ServicoViewModel> listViewServico = _mapper.Map<List<ServicoViewModel>>(listaServicos);
            return View(listViewServico);
        }

        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            ViewData["EquipeId"] = new SelectList(_equipeRepository.ObterTodos(), "IdEquipe", "NomeEquipe");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create(ServicoViewModel servicoView)
        {
            if (ModelState.IsValid)
            {
                var servicoModel = _mapper.Map<Servicos>(servicoView);
                _servicoRepository.CriarNovo(servicoModel);
                _servicoRepository.Salvar();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EquipeId"] = new SelectList(_servicoRepository.ObterTodos(), "IdEquipe", "IdEquipe", servicoView.EquipeId);
            return View(servicoView);
        }

        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servicos = _servicoRepository.ObterPorId(id);
            var servicoModel = _mapper.Map<ServicoViewModel>(servicos);
            if (servicoModel == null)
            {
                return NotFound();
            }
            ViewData["EquipeId"] = new SelectList(_equipeRepository.ObterTodos(), "IdEquipe", "NomeEquipe", servicoModel.EquipeId);
            return View(servicoModel);
        }


        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int id, ServicoViewModel servicoViewModel)
        {
            if (id != servicoViewModel.IdServico)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var servicoModel = _mapper.Map<Servicos>(servicoViewModel);
                    _servicoRepository.Atualizar(servicoModel);
                    _servicoRepository.Salvar();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_servicoRepository.Exists(servicoViewModel.IdServico))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["EquipeId"] = new SelectList(_equipeRepository.ob, "IdEquipe", "IdEquipe", servicos.EquipeId);
            return View(servicoViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var servicos = _servicoRepository.ObterPorId(id);
            _servicoRepository.Deletar(servicos);
            _servicoRepository.Salvar();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Administrador")]
        public IActionResult ListaServicos()
        {
            var listaServicos = _servicoRepository.ObterTodos();
            var listViewServicos = _mapper.Map<List<ServicoViewModel>>(listaServicos);
            return View(listViewServicos);
        }
    }
}

matrix/Views/Home/Administrador.cshtml
<!-- ====== Pricing Section Start -->
    <section
      id="pricing"
      class="
        bg-white
        pt-20
        lg:pt-[120px]
        pb-12
        lg:pb-[90px]
        relative
        z-20
        overflow-hidden
      "
      style="margin-right: 200px; margin-left: 200px; padding-top: 200px;"
    >
      <div class="container">
        <div class="flex flex-wrap -mx-4">
          <div class="w-full px-4">
            <div class="text-center mx-auto mb-[60px] lg:mb-20 max-w-[620px]">
              
              <h2
                class="
                  font-bold
                  text-3xl
                  sm:text-4xl
                  md:text-[40px]
                  text-dark
                  mb-4
                "
              >
                Painel Administrativo
              </h2>
              <p
                class="
                  text-lg
                  sm:text-xl
                  leading-relaxed
                  sm:leading-relaxed
                  text-body-color
                "
              >
                Por aqui você consegue selecionar o item que deseja e dentro dele
                poderá adicionar um novo item, atualizar ou deletar um item já existente.
              </p>
            </div>
          </div>
        </div>

        <div class="flex flex-wrap items-center justify-center">
          
          <div class="w-full md:w-1/2 lg:w-1/3">
            <div
              class="
               
                bg-white
                rounded-xl
                relative
                z-10
                overflow-hidden
                border border-primary border-opacity-20
                shadow-pricing
                py-10
                px-8
                sm:p-12
                lg:py-10 lg:px-6
                xl:p-12
                mb-10
                text-center
                wow
                fadeInUp
              
              "
              data-wow-delay=".1s
              "
            >
              <span
                class="
                  inline-block
                  py-2
                  px-6
                  border border-white
                  rounded-full
                  text-base
                  font-semibold
                  text-primary
                  bg-white
                  uppercase
                  mb-5
                "
              >
              </span>
              
              <h2 class="font-semibold text-primary mb-9 text-[28px]">
                Serviços
              </h2>

              <div class="mb-10">
                  <div>
                <a asp-action="create" asp-controller="servicos" class="text-base font-medium text-black leading-loose mb-1">
                  Adicionar
                </a>
                </div>
                <div>
                    <a asp-action="listaServicos" asp-controller="servicos" class="text-base font-medium text-black leading-loose mb-1">
                  Editar
                </a>
                <span
                class="
                  absolute
                  left-0
                  bottom-0
                  z-[-1]
                  w-14
                  h-14
                  rounded-tr-full
                  block
                  bg-primary
                "
              >
                </div>
              </div>
                
            </div>
          </div>
          <div class="w-full md:w-1/2 lg:w-1/3" style="margin-left: 0px;">
            <div
              class="
               
                bg-white
                rounded-xl
                relative
                z-10
                overflow-hidden
                border border-primary border-opacity-20
                shadow-pricing
                py-10
                px-8
                sm:p-12
                lg:py-10 lg:px-6
                xl:p-12
                mb-10
                text-center
                wow
                fadeInUp
              
              "
              data-wow-delay=".1s
              "
            >
              <span
                class="
                  inline-block
                  py-2
                  px-6
                  border border-white
                  rounded-full
                  text-base
                  font-semibold
                  text-primary
                  bg-white
                  uppercase
                  mb-5
                "
              >
              </span>
              
              <h2 class="font-semibold text-primary mb-9 text-[28px]">
                Postagens
              </h2>

              <div class="mb-10">
                  <div>
                <a asp-action="create" asp-controller="postagems" class="text-base font-medium text-black leading-loose mb-1">
                  Adicionar
                </a>
                </div>
                <div>
                    <a asp-action="ListaPostagens" asp-controller="postagems" class="text-base font-medium text-black leading-loose mb-1">
                  Editar
                </a>
                <span
                class="
                  absolute
                  right-0
                  top-0
                  z-[-1]
                  w-14
                  h-14
                  rounded-bl-full
                  block
                  bg-secondary
                "
              >
              </span>
                </div>
              </div>
                
            </div>
          </div>

          
          </div>        
      </div>
    </section>
    <!-- ====== Pricing Section End -->

matrix/Views/Home/Index.cshtml
@model matrix.Models.Views.HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}
<!-- ====== Banner Section Start -->
<section>
    <div class="imgbanner">
        <img src="https://wallpaperboat.com/wp-content/uploads/2019/08/Abstract-Background-Abstraction-Desktop.jpg" />
    </div>
</section>
<!-- ====== Banner Section End -->

<div class="sectiontitlebanner">
    <div class="sectiontitlebannerchildren"
    <div>
        <h2>
            Como Podemos ajudar seu négocio a evoluir digitalmente?
        </h2>
        <button>
            Saiba mais
        </button>
    </div>
</div>
</div>


<!-- ====== Features Section Start -->
<section class="pt-20 lg:pt-[120px] pb-8 lg:pb-[70px]" id="servicosdiv">
    <div class="container sectionstartnew">
        <div class="flex flex-wrap -mx-4">
            <div class="w-full px-4">
                <div class="mb-12 lg:mb-20 max-w-[620px]">
                    <span class="font-semibold text-lg text-primary mb-2 block">
                        Features
                    </span>
                    <h2 class="
                  font-bold
                  text-3xl
                  sm:text-4xl
                  md:text-[42px]
                  text-dark
                  mb-4
                ">
                        Nossa lista de serviços
                    </h2>
                    <p class="
                  text-lg
                  sm:text-xl
                  leading-relaxed
                  sm:leading-relaxed
                  text-body-color
                ">
                        Temos uma lista vasta de serviços que podem facilitar o seu dia a dia, confira abaixo alguns deles.
                    </p>
                </div>
            </div>
        </div>
        <div class="flex flex-wrap -mx-3">
            @foreach(var item in Model.servicos)
            {
@*                @Html.Partial("_Servico", @Model.servicos[i]) *@   
                <partial name="_Servico" model="item" />
            }
            
        </div>
        <a asp-action="index" asp-controller="Servicos"
                       class="font-medium text-base text-body-color hover:text-primary">
                        Learn More
                    </a>
    </div>
</section>
<!-- ====== Testimonials Start ====== -->
<section id="blogdiv" class="pt-20 md:pt-[120px] bg-[#f3f4ff]" style="padding: 100px 0 100px 0" >
    <div class="sectionstartnew px-4">
        <div class="flex flex-wrap">
            <div class="w-full mx-4">
                <div class="text-center mx-auto mb-[60px] lg:mb-20 max-w-[620px]">
                    <span class="font-semibold text-lg text-primary mb-2 block">
                        Postagens
                    </span>
                    <h2 class="
                  font-bold
                  text-3xl
                  sm:text-4xl
                  md:text-[42px]
                  text-dark
                  mb-4
                ">
                        Destaques no nosso blog
                    </h2>
                    <p class="
                  text-lg
                  sm:text-xl
                  leading-relaxed
                  sm:leading-relaxed
                  text-body-color
                ">
                        Como forma de conhecimento, possuimos essa lista de postagens para que você conheça um pouco mais
                        o mundo da tecnologia.
                    </p>
                </div>
            </div>
        </div>

        <div class="flex flex-wrap">
            @foreach(var postagem in Model.Postagens)
            {
                <partial name="_Postagem" model="postagem"/>
            }      
            </div>
            <div class="centralizarElemento">
            <a asp-action="index" asp-controller="Postagems"
                       class="font-medium text-base text-body-color hover:text-primary">
                        Learn More
                    </a>
                    </div>
        </div>
</section>